/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yhuryekwwmonyjjezipw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodXJ5ZWt3d21vbnlqamV6aXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyMzU2NTcsImV4cCI6MjA5NjgxMTY1N30.0UyJyo-prXU4ENEfbUajHud8-T37-k_J7Ad-J72YIDY"